version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
  db:
    build:
      context: .
      dockerfile: database.Dockerfile
    environment:
      MYSQL_DATABASE: student_vaccination_db
      MYSQL_ROOT_PASSWORD: root
